name: Build Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set repository name to lowercase
        run: echo "REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set current date as env variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: Build and push image to ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: ./Containerfile
          push: true
          tags: >
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }},
            ghcr.io/${{ env.REPO_NAME }}:${{ env.DATE }},
            ghcr.io/${{ env.REPO_NAME }}:38,
            ghcr.io/${{ env.REPO_NAME }}:latest
          platforms: linux/amd64